// <auto-generated />
using System;
using Lab8_CombinedLoading.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab8_CombinedLoading.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    [Migration("20260202083445_Moi")]
    partial class Moi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab8_CombinedLoading.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Instructor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Credits = 4,
                            Instructor = "ThS. Nguyễn Văn A",
                            Title = "Lập trình C#"
                        },
                        new
                        {
                            CourseId = 2,
                            Credits = 3,
                            Instructor = "TS. Trần Thị B",
                            Title = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            CourseId = 3,
                            Credits = 4,
                            Instructor = "ThS. Lê Văn C",
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            CourseId = 4,
                            Credits = 3,
                            Instructor = "ThS. Lê Văn C",
                            Title = "Entity Framework"
                        },
                        new
                        {
                            CourseId = 5,
                            Credits = 3,
                            Instructor = "ThS. Phạm Văn D",
                            Title = "Phát triển Web"
                        });
                });

            modelBuilder.Entity("Lab8_CombinedLoading.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 8.5m,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 7.0m,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 9.0m,
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 5,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 8.0m,
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 6,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 9.5m,
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 7,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 8,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 7.5m,
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 9,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 8.0m,
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 10,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 6.5m,
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 11,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 12,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 13,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 8.5m,
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 14,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Lab8_CombinedLoading.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Class = "CNTT-K65",
                            Email = "an.nguyen@email.com",
                            Name = "Nguyễn Văn An"
                        },
                        new
                        {
                            StudentId = 2,
                            Class = "CNTT-K65",
                            Email = "binh.tran@email.com",
                            Name = "Trần Thị Bình"
                        },
                        new
                        {
                            StudentId = 3,
                            Class = "CNTT-K66",
                            Email = "cuong.le@email.com",
                            Name = "Lê Hoàng Cường"
                        },
                        new
                        {
                            StudentId = 4,
                            Class = "CNTT-K66",
                            Email = "dung.pham@email.com",
                            Name = "Phạm Thu Dung"
                        },
                        new
                        {
                            StudentId = 5,
                            Class = "CNTT-K67",
                            Email = "duc.hoang@email.com",
                            Name = "Hoàng Minh Đức"
                        });
                });

            modelBuilder.Entity("Lab8_CombinedLoading.Models.Enrollment", b =>
                {
                    b.HasOne("Lab8_CombinedLoading.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab8_CombinedLoading.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Lab8_CombinedLoading.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Lab8_CombinedLoading.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
